DjangoPollsProject/mysite/mysite/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('polls/', include('polls.urls')),
]

DjangoPollsProject/mysite/polls/urls.py
from django.urls import path

from . import views

# name parametresi daha dinamik url oluşturmak içindir

# app_name uygulama isim alanı oluşturmak için
# farıklı uygulamalarda aynı isimde sayfalar varsa karışıklığı engeller
app_name = "polls"

# yeni generic view url pattern
urlpatterns = [
    path('', views.IndexView.as_view(), name='index'),
    path("<int:pk>/", views.DetailView.as_view(), name="detail"),
    path("<int:pk>/results/", views.ResultsView.as_view(), name="results"),
    path("<int:question_id>/vote/", views.vote, name="vote"),
]


# eski tarz url pattern
"""
urlpatterns = [
    path('', views.index, name='index'),
    path("<int:question_id>/", views.detail, name="detail"), # /polls/5/
    path("<int:question_id>/results/", views.results, name="results"), # /polls/5/results
    path("<int:question_id>/vote/", views.vote, name="vote"), # /polls/5/vote
]
"""

DjangoPollsProject/mysite/polls/models.py
from django.db import models
from django.utils import timezone
import datetime
# Create your models here.

class Question(models.Model):
    question_text = models.CharField(max_length=200)
    pub_date = models.DateTimeField('date published')

    def __str__(self):
        return self.question_text

    def was_published_recently(self):
        now = timezone.now()
        
        # bug fixed with test. future question.
        #return self.pub_date >= timezone.now() - datetime.timedelta(days=1)

        return now - datetime.timedelta(days=1) <= self.pub_date <= now
    
    was_published_recently.admin_order_field = 'pub_date'
    was_published_recently.boolean = True
    was_published_recently.short_description = 'Published recently?'


class Choice(models.Model):
    question = models.ForeignKey(Question, on_delete=models.CASCADE)
    choice_text = models.CharField(max_length=200)
    votes = models.IntegerField(default=0)

    def __str__(self):
        return self.choice_text

DjangoPollsProject/mysite/polls/views.py
from django.shortcuts import render, HttpResponse, get_object_or_404
from django.http import HttpResponseRedirect
from django.urls import reverse
from django.views import generic
from django.utils import timezone
from .models import Question, Choice

# Create your views here.

class IndexView(generic.ListView):
    template_name = "polls/index.html"
    context_object_name = "latest_question_list"

    def get_queryset(self):
        """
        return last 5 question
        not including those set to be  published in the future
        """
        #
        #return Question.objects.order_by("-pub_date")[:5]
        
        # return pub_date lest then or equal then timezone.now()
        return Question.objects.filter(
            pub_date__lte=timezone.now()
        ).order_by("-pub_date")[:5]


class DetailView(generic.DetailView):
    model = Question
    template_name = 'polls/detail.html'


class ResultsView(generic.DetailView):
    model = Question
    template_name = "polls/results.html"


# eski usül generic view kullanılmadan yapılan view fonksiyonları.
# hesap makinesi kullanmadan önce biraz matematik bilmelisin :)
"""
def index(request):
    latest_question_list = Question.objects.order_by("-pub_date")[:5]
    context = {
        "latest_question_list": latest_question_list
    }
    return render(request, "polls/index.html" ,context)


def detail(request, question_id):
    question =get_object_or_404(Question, pk=question_id)
    return render(request, "polls/detail.html", {"question": question})


def results(request, question_id):
    question = get_object_or_404(Question, pk=question_id)
    return render(request, "polls/results.html", {"question": question})
"""

# vote view inde bir değişikliğe gerek yok
def vote(request, question_id):
    """
    a
    """
    question = get_object_or_404(Question, pk=question_id)
    try:
        selected_choice = question.choice_set.get(pk=request.POST["choice"])
    except (KeyError, Choice.DoesNotExist):
        # question oylama formunu tekrar görüntüle
        return render(request, "polls/detail.html", {
            "question": question, 
            "error_message": "you didint select choice"
            })
    else:
        selected_choice.votes += 1
        selected_choice.save()
        # her zaman HttpResponseRedirect geri dönder
        # reverse "polls:results" urlini hardcoded url adresine çevirir polls/2/results/ gibi
        return HttpResponseRedirect(reverse("polls:results", args=(question.id,)))

DjangoPollsProject/mysite/polls/templates/polls/detail.html
<h1>{{ question.question_text}}</h1>

{% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}

<form action="{% url 'polls:vote' question.id%}" method="POST">
    {% csrf_token %}
    {% for choice in question.choice_set.all %}
        <input type="radio" name="choice" id="choice{{ forloop.counter }}" value="{{ choice.id }}">
        <label for="choice{{ forloop.counter }}">{{ choice.choice_text }}</label><br>
    {% endfor %}
    <input type="submit" value="Vote">
</form>

DjangoPollsProject/mysite/polls/templates/polls/index.html
{% load static %}

<link rel="stylesheet" type="text/css" href="{% static 'polls/style.css' %}">

{% if latest_question_list %}
    <ul>
        {% for question in latest_question_list %}
            <!-- polls:detail uygulama:urlismi şeklinde -->
            <li><a href="{% url 'polls:detail' question.id%}">{{question.question_text}}</a></li>
        {% endfor %}
    </ul>
    {% else %}
        <p>No poles are aweilable</p>
{% endif %}

DjangoPollsProject/mysite/polls/templates/polls/results.html
<h1>{{ question.question_text }}</h1>

<ul>
    {% for choice in question.choice_set.all %}
        <li>{{ choice.choice_text }} -- {{ choice.votes }} vote{{ choice.votes|pluralize }}</li>
    {% endfor %}
</ul>

<a href="{% url 'polls:detail' question.id %}">Vote again?</a>